version: "3.4"
services:
  redis-master:
    image: redis:bullseye
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  redis-slave:
    image: redis:bullseye
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6380:6379"
  postgres_db:
    image: postgres:bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "demodb"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
  api:
    image: redis-demo-api:latest
    ports:
      - "5050:80"
    depends_on:
      - "postgres_db"
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"